# ModPanel Configuration File

# Web server configuration
web-server:
  port: 9999 # Port for the web server default is 9999
  proxy-mode: false # If true, trust X-Forwarded-For header (enable only if behind a reverse proxy like Nginx)
  ip-privacy: true # If true, only the first two digits of the IP address will be showed on logs (e.g. 192.168.x.x)

  # Connection spam protection ! DO NOT DISABLE UNLESS YOU KNOW WHAT YOU ARE DOING !
  connection-limit:
    enabled: true # Do not disable this unless you know what you are doing (default is true)
    ban-after: 10 # Number of tries before banning an IP (default is 10)
    ban-duration: 600 # Ban duration in seconds (default is 300 seconds = 5 minutes)
    permanent-ban-threshold: 2 # Number of bans before permanently banning an IP (default is 2)

# Discord bot configuration
discord_token: "none" # Your Discord bot token here (default is "none" which disables the bot)
