name: ModPanel
version: alpha-0.2.2s
main: com.xl1te.modpanel.Main
api-version: 1.19
description: A powerful moderation panel for your Minecraft server.
author: xl1te
url: https://github.com/lighscent/ModPanel
load: POSTWORLD
commands:
  mp:
    description: ModPanel commands
    usage: /<command> reload
    aliases: [modpanel]
    permission: mp.admin
permissions:
  mp.admin:
    description: Allows access to ModPanel admin commands
    default: op
libraries:
  - com.h2database:h2:2.4.240